name: Build Firmware (PR) on Venice

permissions:
  contents: read

on:
  pull_request:
    paths:
    - 'boards/venice/**'
    - 'boards/common/**'
    - 'boards/common_extras/**'
    - 'patches/venice/**'
    - 'scripts/openmanet_setup.sh'
    - '.github/workflows/build-firmware.yml'
    - '.github/workflows/build-pr-venice.yml'
    - 'include/kernel*'
    - 'package/kernel/**'
    - 'target/linux/imx/**'
    - 'feeds.conf.default'

jobs:
  build-venice:
    name: Build Venice
    uses: ./.github/workflows/build-firmware.yml
    with:
      board: venice
      target: imx
      subtarget: cortexa53
      description: "Gateworks Venice"
