name: Build Firmware (PR) on halowlink2

permissions:
  contents: read

on:
  pull_request:
    paths:
    - 'boards/halowlink2/**'
    - 'boards/common/**'
    - 'boards/common_extras/**'
    - 'patches/halowlink2/**'
    - 'scripts/openmanet_setup.sh'
    - '.github/workflows/build-firmware.yml'
    - '.github/workflows/build-pr-halowlink2.yml'
    - 'include/kernel*'
    - 'package/kernel/**'
    - 'target/linux/ramips/**'
    - 'feeds.conf.default'

jobs:
  build-halowlink2:
    name: Build HalowLink2
    uses: ./.github/workflows/build-firmware.yml
    with:
      board: halowlink2
      target: ramips
      subtarget: mt7621
      description: "HalowLink 2 (MT7621)"
